#!/bin/sh

# SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"

DESKTOP_SESSION=Hyprland
XDG_CURRENT_DESKTOP=Hyprland
XDG_SESSION_DESKTOP=Hyprland
XDG_SESSION_TYPE=wayland

XKB_DEFAULT_LAYOUT=us

LIBSEAT_BACKEND=logind

QT_AUTO_SCREEN_SCALE_FACTOR=1
QT_QPA_PLATFORM="wayland;xcb"
# QT_QPA_PLATFORM=wayland-egl
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
QT_QPA_PLATFORMTHEME=qt5ct
# QT_WAYLAND_FORCE_DPI=physical

# MOZ_ENABLE_WAYLAND=1

_JAVA_AWT_WM_NONEREPARENTING=1

CLUTTER_BACKEND=wayland

SDL_VIDEODRIVER=wayland

# GDK_BACKEND="wayland,x11"
GDK_BACKEND=wayland

WLR_DRM_DEVICES=/dev/dri/card0

[ "$(tty)" = "/dev/tty1" ] && exec Hyprland
