#!/usr/bin/env bash

SWAY_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/sway"

# sway specific environment
if [[ -f $SWAY_CONFIG_HOME/env ]]; then
  set -a
  # shellcheck disable=SC1090
  . "$SWAY_CONFIG_HOME/env"
  set +a
fi

# exec systemd-cat --identifier sway dbus-run-session -- /usr/bin/sway "$@"
exec /usr/bin/sway "$@"
