-- vim.cmd("autocmd! BufNew,BufNewFile,Bufread *ssh.cfg :setfiletype sshconfig")

-- vim.filetype.add({
-- 	-- filename = {
-- 	-- 	[".env"] = "config",
-- 	-- },
-- 	-- extension = { j2 = "sshconfig" },
-- 	pattern = {
-- 		["*/.ssh/config.d/*"] = "sshconfig",
-- 	},
-- })
