return {
  black = require('modules.lsp.efm.black'),
  buf = require('modules.lsp.efm.buf'),
  buildifier = require('modules.lsp.efm.buildifier'),
  eslint = require('modules.lsp.efm.eslint'),
  fixjson = require('modules.lsp.efm.fixjson'),
  flake8 = require('modules.lsp.efm.flake8'),
  goimports = require('modules.lsp.efm.goimports'),
  golint = require('modules.lsp.efm.golint'),
  htmllint = require('modules.lsp.efm.htmllint'),
  isort = require('modules.lsp.efm.isort'),
  jq = require('modules.lsp.efm.jq'),
  jsonlint = require('modules.lsp.efm.jsonlint'),
  luafmt = require('modules.lsp.efm.luafmt'),
  markdownlint = require('modules.lsp.efm.markdownlint'),
  misspell = require('modules.lsp.efm.misspell'),
  mypy = require('modules.lsp.efm.mypy'),
  prettier = require('modules.lsp.efm.prettier'),
  shellcheck = require('modules.lsp.efm.shellcheck'),
  shfmt = require('modules.lsp.efm.shfmt'),
  stylelint = require('modules.lsp.efm.stylelint'),
  terraform = require('modules.lsp.efm.terraform'),
  vint = require('modules.lsp.efm.vint'),
  yamllint = require('modules.lsp.efm.yamllint'),
  phpcsfixer = require('modules.lsp.efm.phpcsfixer'),
}
