export enum Types {
  SELECT = 'PERSON_SELECT',

  LIST_FETCH = 'PERSON_LIST_FETCH',
  LIST_FETCH_REQUEST = 'PERSON_LIST_FETCH_REQUEST',
  LIST_FETCH_SUCCESS = 'PERSON_LIST_FETCH_SUCCESS',
  LIST_FETCH_FAILURE = 'PERSON_LIST_FETCH_FAILURE',

  FETCH = 'PERSON_FETCH',
  FETCH_REQUEST = 'PERSON_FETCH_REQUEST',
  FETCH_SUCCESS = 'PERSON_FETCH_SUCCESS',
  FETCH_FAILURE = 'PERSON_FETCH_FAILURE',
}
