export const moduleName = 'websocket'

export enum WebsocketTypes {
  CONNECT = 'WEBSOCKET__CONNECT',
  CONNECTING = 'WEBSOCKET__CONNECTING',
  CONNECTED = 'WEBSOCKET__CONNECTED',
  DISCONNECT = 'WEBSOCKET__DISCONNECT',
  DISCONNECTED = 'WEBSOCKET__DISCONNECTED',
  ERROR = 'WEBSOCKET__ERROR',
  SUBSCRIBE = 'WEBSOCKET__SUBSCRIBE',
  SUBSCRIBED = 'WEBSOCKET__SUBSCRIBED',
  UNSUBSCRIBE = 'WEBSOCKET__UNSUBSCRIBE',
  UNSUBSCRIBED = 'WEBSOCKET__UNSUBSCRIBED',
}
