export enum Types {
  USER_SELECT = 'USER_SELECT',

  USER_LIST_FETCH = 'USER_LIST_FETCH',
  USER_LIST_FETCH_REQUEST = 'USER_LIST_FETCH_REQUEST',
  USER_LIST_FETCH_SUCCESS = 'USER_LIST_FETCH_SUCCESS',
  USER_LIST_FETCH_FAILURE = 'USER_LIST_FETCH_FAILURE',

  USER_FETCH = 'USER_FETCH',
  USER_FETCH_REQUEST = 'USER_FETCH_REQUEST',
  USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS',
  USER_FETCH_FAILURE = 'USER_FETCH_FAILURE',
}
