export enum Types {
  SELECT = 'ORGANIZATION_SELECT',

  LIST_FETCH = 'ORGANIZATION_LIST_FETCH',
  LIST_FETCH_REQUEST = 'ORGANIZATION_LIST_FETCH_REQUEST',
  LIST_FETCH_SUCCESS = 'ORGANIZATION_LIST_FETCH_SUCCESS',
  LIST_FETCH_FAILURE = 'ORGANIZATION_LIST_FETCH_FAILURE',

  FETCH = 'ORGANIZATION_FETCH',
  FETCH_REQUEST = 'ORGANIZATION_FETCH_REQUEST',
  FETCH_SUCCESS = 'ORGANIZATION_FETCH_SUCCESS',
  FETCH_FAILURE = 'ORGANIZATION_FETCH_FAILURE',
}
