export enum Types {
  SELECT = 'ORDER_SELECT',

  LIST_FETCH = 'ORDER_LIST_FETCH',
  LIST_FETCH_REQUEST = 'ORDER_LIST_FETCH_REQUEST',
  LIST_FETCH_SUCCESS = 'ORDER_LIST_FETCH_SUCCESS',
  LIST_FETCH_FAILURE = 'ORDER_LIST_FETCH_FAILURE',

  FETCH = 'ORDER_FETCH',
  FETCH_REQUEST = 'ORDER_FETCH_REQUEST',
  FETCH_SUCCESS = 'ORDER_FETCH_SUCCESS',
  FETCH_FAILURE = 'ORDER_FETCH_FAILURE',
}
