export enum Types {
  CONNECT = 'WEBSOCKET__CONNECT',
  CONNECTING = 'WEBSOCKET__CONNECTING',
  CONNECTED = 'WEBSOCKET__CONNECTED',
  SEND = 'WEBSOCKET__SEND',
  SEND_RPC = 'WEBSOCKET__SEND_RPC',
  DISCONNECT = 'WEBSOCKET__DISCONNECT',
  DISCONNECTED = 'WEBSOCKET__DISCONNECTED',
  ERROR = 'WEBSOCKET__ERROR',
}
