export enum AppNavigationTypes {
  SELECT_MODULE = 'APP_NAVIGATION__SELECT_MODULE',

  LIST_FETCH_MODULES = 'APP_NAVIGATION__LIST_FETCH_MODULES',
  LIST_FETCH_MODULES_REQUEST = 'APP_NAVIGATION__LIST_FETCH_MODULES_REQUEST',
  LIST_FETCH_MODULES_SUCCESS = 'APP_NAVIGATION__LIST_FETCH_MODULES_SUCCESS',
  LIST_FETCH_MODULES_FAILURE = 'APP_NAVIGATION__LIST_FETCH_MODULES_FAILURE',

  FETCH_MODULE = 'APP_NAVIGATION__FETCH_MODULE',
  FETCH_MODULE_REQUEST = 'APP_NAVIGATION__FETCH_MODULE_REQUEST',
  FETCH_MODULE_SUCCESS = 'APP_NAVIGATION__FETCH_MODULE_SUCCESS',
  FETCH_MODULE_FAILURE = 'APP_NAVIGATION__FETCH_MODULE_FAILURE',

  LOADED = 'APP_NAVIGATION__LOADED',
  LIST_MODULES_REQUEST = 'APP_NAVIGATION__LIST_MODULES_REQUEST',
  LIST_MODULES_RESPONSE = 'APP_NAVIGATION__LIST_MODULES_RESPONSE',
  ListModulesResponse = 'ListModulesResponse',
}
