export enum Types {
  SELECT = 'ACCOUNT_SELECT',

  LIST_FETCH = 'ACCOUNT_LIST_FETCH',
  LIST_FETCH_REQUEST = 'ACCOUNT_LIST_FETCH_REQUEST',
  LIST_FETCH_SUCCESS = 'ACCOUNT_LIST_FETCH_SUCCESS',
  LIST_FETCH_FAILURE = 'ACCOUNT_LIST_FETCH_FAILURE',

  FETCH = 'ACCOUNT_FETCH',
  FETCH_REQUEST = 'ACCOUNT_FETCH_REQUEST',
  FETCH_SUCCESS = 'ACCOUNT_FETCH_SUCCESS',
  FETCH_FAILURE = 'ACCOUNT_FETCH_FAILURE',
}
