export enum Types {
  ACCOUNT_WIDGET_TOGGLE = 'UI_ACCOUNT_WIDGET_TOGGLE',
  ACCOUNT_WIDGET_DISPLAY = 'UI_ACCOUNT_WIDGET_DISPLAY',

  APPLICATION_LOAD = 'UI_APPLICATION_LOAD',
  APPLICATION_LOADING = 'UI_APPLICATION_LOADING',
  APPLICATION_LOADED = 'UI_APPLICATION_LOADED',
  APPLICATION_CLOSE = 'UI_APPLICATION_CLOSE',
  APPLICATION_CLOSED = 'UI_APPLICATION_CLOSED',

  ACTION_CENTER_TOGGLE = 'UI_ACTION_CENTER_TOGGLE',
  ACTION_CENTER_DISPLAY = 'UI_ACTION_CENTER_DISPLAY',
  ACTION_CENTER_DISPLAYED = 'UI_ACTION_CENTER_DISPLAYED',
  ACTION_CENTER_HIDE = 'UI_ACTION_CENTER_HIDE',
  ACTION_CENTER_HIDDEN = 'UI_ACTION_CENTER_HIDDEN',
}
