export enum Types {
  SELECT = 'APPLICATION__SELECT',

  LIST_FETCH = 'APPLICATION__LIST_FETCH',
  LIST_FETCH_REQUEST = 'APPLICATION__LIST_FETCH_REQUEST',
  LIST_FETCH_SUCCESS = 'APPLICATION__LIST_FETCH_SUCCESS',
  LIST_FETCH_FAILURE = 'APPLICATION__LIST_FETCH_FAILURE',

  FETCH = 'APPLICATION__FETCH',
  FETCH_REQUEST = 'APPLICATION__FETCH_REQUEST',
  FETCH_SUCCESS = 'APPLICATION__FETCH_SUCCESS',
  FETCH_FAILURE = 'APPLICATION__FETCH_FAILURE',

  START = 'APPLICATION__START',
  STARTING = 'APPLICATION__STARTING', // Show the loader while loading the data
  STARTED = 'APPLICATION__STARTED',
  STOP = 'APPLICATION__STOP',
  STOPPED = 'APPLICATION__STOPPED',
  FAILED = 'APPLICATION__FAILED', // Show the error if any or RBAC restrictions

  GET = 'APPLICATION__GET',
  GET_SUCCESS = 'APPLICATION__GET_SUCCESS',
  LIST_APPLICATIONS_RESPONSE = 'APPLICATION__LIST_APPLICATIONS_RESPONSE',
  ListApplicationsResponse = 'ListApplicationsResponse',
}
